web_dev/run_django/dwarfrabbitclub/urls.py
#i created this file
from django.urls import path
from . import views #the order of the urls matter because for instance if i have str:confession first, then it will always catch my urls

app_name = 'dwarfrabbitclub' #helps with namespace collision errors
urlpatterns = [
    path("",views.root, name='root'),
    path("entry_granted",views.entry,name='entry'),
    path("entry_granted/to_do",views.to_do,name='to_do'),
    path("create/user",views.create_user,name='create_user'),
    path("pending/user",views.pending_user,name='pending_user'),
    path("modify_pending",views.modify_pending,name = 'modify_pending'),
    
   
]

web_dev/run_django/madbunnyclub/urls.py
#i created this file
from django.urls import path
from . import views #the order of the urls matter because for instance if i have str:confession first, then it will always catch my urls

app_name = 'madbunnyclub' #helps with namespace collision errors
urlpatterns = [
    path("",views.root, name='root'),
    path("tasks",views.index, name='index'),
    path("addTask",views.addTask,name='add'),
    
    path("names", views.names,name="names"), 
    path("name/habitually",views.habitually, name = 'habit'),
    path("<str:confession>",views.confess,name='confess'),
    
]

web_dev/run_django/run_django/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('madbunnyclub/',include("madbunnyclub.urls")), #a
    path('dwarfrabbitclub/',include("dwarfrabbitclub.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

web_dev/run_django/madbunnyclub/models.py
from django.db import models

    

web_dev/run_django/madbunnyclub/views.py
from django.http import HttpResponse #a
from django.shortcuts import render
import datetime
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    #priority = forms.IntegerField(label="Priority",min_value=1,max_value=5)

# Create your views here.
tasks = []
def root(request):
    return render(request,"madbunnyclub/root.html")
def index(request): #http request
#    if "tasks" not in request.session:
#        request.session["tasks"] = []
    return render(request,"madbunnyclub/index.html",{"tasks":tasks})#request.session["tasks"]

def names(request):
    date = datetime.datetime.now()
    
    return HttpResponse(f'Hello,Katja B. Puig {date.month} {date.day}')

def habitually(request):
    return HttpResponse("I look in the mirror habitually")

def confess(request,confession):
    return render(request,"madbunnyclub/hide.html",{"code":confession,"sum":False}) #the key should be the variable name in an html



#common pattern in here
def addTask(request): # add a check because add can request or post
    if request.method == 'POST':
        #process the request 
        form = NewTaskForm(request.POST) #contains all data that user submitted
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task) #request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse('madbunnyclub:index'))
        else: return render(request, "madbunnyclub/add.html", {"form":form}) #server side validation in case client side is not up to date
    
    #the get case 
    return render(request,"madbunnyclub/add.html",{'form':NewTaskForm()}) # adde4d {'form'...} replace the <input> line in add with {{ form }} <input type="text" name="task">

web_dev/run_django/madbunnyclub/templates/madbunnyclub/add.html
{%extends "madbunnyclub/layout.html" %}
 
{% block body %}  
        <h1> add a task </h1>
        <form action="{%url 'madbunnyclub:add' %}" method = 'post'>
            {%csrf_token%}
            {{ form}}
            
            <input type="submit">
        </form>
        <a href="{% url 'madbunnyclub:index' %}"> View Tasks </a>
{% endblock %}

web_dev/run_django/madbunnyclub/templates/madbunnyclub/hide.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Hide </title>
    </head>
    <body>
        <h1>Madbunny {{code}}</h1>
        {% if sum%}
            <h1> YES </h1>
        {%else%}
            <h1> No </h1>
        {%endif%} 
    </body>
</html>

web_dev/run_django/madbunnyclub/templates/madbunnyclub/index.html
{%extends "madbunnyclub/layout.html" %}
 
{% block body %}    
        <h1> tasks </h1>  
        <ul>
            {% for task in tasks %}
                <li> {{ task }} </li>
            {% empty%}
                <li> No Tasks </li>
            {% endfor %}
        </ul>
        <a href="{%url 'madbunnyclub:add' %}">Add a New Task</a>
{%endblock%}

web_dev/run_django/madbunnyclub/templates/madbunnyclub/layout.html
{%load static%}


<!DOCTYPE html>
<html lang="en">
    <head>
        <title> List </title>
        <link href="{% static 'madbunnyclub/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

web_dev/run_django/madbunnyclub/templates/madbunnyclub/root.html
{%load static%}
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Welcome to the home of Rabbit Ranching</title>
    </head>
    <body>  
        
        <img src="{% static 'madbunnyclub/media/bunnies.jpg' %}" alt="closerttt" width = "500" >
        
        <a href = "{% url 'dwarfrabbitclub:root'%}">
            SecretPortal
        </a>
        
    </body>
</html>